// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_common_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FusionObstacleCategory_common_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_geometry_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Point2Df_geometry_2eproto;
namespace davinci_adas {
namespace apa {
namespace common {
class ParkingSlotPointsScoreDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ParkingSlotPointsScore> _instance;
} _ParkingSlotPointsScore_default_instance_;
class ObstaclesAroundVehicleDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ObstaclesAroundVehicle> _instance;
} _ObstaclesAroundVehicle_default_instance_;
class ParkingSlotLocationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ParkingSlotLocation> _instance;
} _ParkingSlotLocation_default_instance_;
class FusionObstacleCategoryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FusionObstacleCategory> _instance;
} _FusionObstacleCategory_default_instance_;
class ObstacleObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ObstacleObject> _instance;
} _ObstacleObject_default_instance_;
}  // namespace common
}  // namespace apa
}  // namespace davinci_adas
static void InitDefaultsscc_info_FusionObstacleCategory_common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::davinci_adas::apa::common::_FusionObstacleCategory_default_instance_;
    new (ptr) ::davinci_adas::apa::common::FusionObstacleCategory();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FusionObstacleCategory_common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FusionObstacleCategory_common_2eproto}, {}};

static void InitDefaultsscc_info_ObstacleObject_common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::davinci_adas::apa::common::_ObstacleObject_default_instance_;
    new (ptr) ::davinci_adas::apa::common::ObstacleObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ObstacleObject_common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ObstacleObject_common_2eproto}, {
      &scc_info_FusionObstacleCategory_common_2eproto.base,
      &scc_info_Point2Df_geometry_2eproto.base,}};

static void InitDefaultsscc_info_ObstaclesAroundVehicle_common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::davinci_adas::apa::common::_ObstaclesAroundVehicle_default_instance_;
    new (ptr) ::davinci_adas::apa::common::ObstaclesAroundVehicle();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ObstaclesAroundVehicle_common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ObstaclesAroundVehicle_common_2eproto}, {}};

static void InitDefaultsscc_info_ParkingSlotLocation_common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::davinci_adas::apa::common::_ParkingSlotLocation_default_instance_;
    new (ptr) ::davinci_adas::apa::common::ParkingSlotLocation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ParkingSlotLocation_common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ParkingSlotLocation_common_2eproto}, {
      &scc_info_Point2Df_geometry_2eproto.base,}};

static void InitDefaultsscc_info_ParkingSlotPointsScore_common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::davinci_adas::apa::common::_ParkingSlotPointsScore_default_instance_;
    new (ptr) ::davinci_adas::apa::common::ParkingSlotPointsScore();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ParkingSlotPointsScore_common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ParkingSlotPointsScore_common_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_common_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_common_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_common_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_common_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, p0_score_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, p1_score_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, p2_score_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotPointsScore, p3_score_),
  0,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstaclesAroundVehicle, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstaclesAroundVehicle, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstaclesAroundVehicle, front_free_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstaclesAroundVehicle, left_free_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstaclesAroundVehicle, right_free_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, p0_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, p1_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, p2_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ParkingSlotLocation, p3_),
  0,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::FusionObstacleCategory, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::FusionObstacleCategory, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::FusionObstacleCategory, img_category_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::FusionObstacleCategory, ultr_category_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_id_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_score_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_tag_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_closest_point_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_velocity_),
  PROTOBUF_FIELD_OFFSET(::davinci_adas::apa::common::ObstacleObject, obs_points_),
  3,
  4,
  0,
  1,
  2,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::davinci_adas::apa::common::ParkingSlotPointsScore)},
  { 13, 21, sizeof(::davinci_adas::apa::common::ObstaclesAroundVehicle)},
  { 24, 33, sizeof(::davinci_adas::apa::common::ParkingSlotLocation)},
  { 37, 44, sizeof(::davinci_adas::apa::common::FusionObstacleCategory)},
  { 46, 57, sizeof(::davinci_adas::apa::common::ObstacleObject)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::davinci_adas::apa::common::_ParkingSlotPointsScore_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::davinci_adas::apa::common::_ObstaclesAroundVehicle_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::davinci_adas::apa::common::_ParkingSlotLocation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::davinci_adas::apa::common::_FusionObstacleCategory_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::davinci_adas::apa::common::_ObstacleObject_default_instance_),
};

const char descriptor_table_protodef_common_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014common.proto\022\027davinci_adas.apa.common\032"
  "\016geometry.proto\"`\n\026ParkingSlotPointsScor"
  "e\022\020\n\010p0_score\030\001 \001(\002\022\020\n\010p1_score\030\002 \001(\002\022\020\n"
  "\010p2_score\030\003 \001(\002\022\020\n\010p3_score\030\004 \001(\002\"S\n\026Obs"
  "taclesAroundVehicle\022\022\n\nfront_free\030\001 \001(\010\022"
  "\021\n\tleft_free\030\002 \001(\010\022\022\n\nright_free\030\003 \001(\010\"\331"
  "\001\n\023ParkingSlotLocation\022/\n\002p0\030\001 \001(\0132#.dav"
  "inci_adas.apa.geometry.Point2Df\022/\n\002p1\030\002 "
  "\001(\0132#.davinci_adas.apa.geometry.Point2Df"
  "\022/\n\002p2\030\003 \001(\0132#.davinci_adas.apa.geometry"
  ".Point2Df\022/\n\002p3\030\004 \001(\0132#.davinci_adas.apa"
  ".geometry.Point2Df\"\244\001\n\026FusionObstacleCat"
  "egory\022D\n\014img_category\030\001 \001(\0162..davinci_ad"
  "as.apa.common.ImageObstacleCategory\022D\n\ru"
  "ltr_category\030\002 \001(\0162-.davinci_adas.apa.co"
  "mmon.UltrObstacleCategory\"\251\002\n\016ObstacleOb"
  "ject\022\016\n\006obs_id\030\001 \001(\r\022\021\n\tobs_score\030\002 \001(\002\022"
  "@\n\007obs_tag\030\003 \001(\0132/.davinci_adas.apa.comm"
  "on.FusionObstacleCategory\022>\n\021obs_closest"
  "_point\030\004 \001(\0132#.davinci_adas.apa.geometry"
  ".Point2Df\0229\n\014obs_velocity\030\005 \001(\0132#.davinc"
  "i_adas.apa.geometry.Point2Df\0227\n\nobs_poin"
  "ts\030\006 \003(\0132#.davinci_adas.apa.geometry.Poi"
  "nt2Df*\273\003\n\025ImageObstacleCategory\022\021\n\rSEG_F"
  "REESPACE\020\000\022\016\n\nSEG_PERSON\020\001\022\014\n\010SEG_WALL\020\002"
  "\022\013\n\007SEG_CAR\020\003\022\r\n\tSEG_OTHER\020\004\022\022\n\016SEG_WHEE"
  "LCHAIR\020\005\022\025\n\021SEG_BABY_CARRIAGE\020\006\022\024\n\020SEG_T"
  "RAFFIC_CONE\020\007\022\030\n\024SEG_GROUND_LOCK_OPEN\020\010\022"
  "\020\n\014SEG_ROADSIDE\020\t\022\032\n\026SEG_PARKING_SPACE_L"
  "INE\020\n\022\026\n\022SEG_ZEBRA_CROSSING\020\013\022\024\n\020SEG_NO_"
  "STOP_LINE\020\014\022\025\n\021SEG_WHEEL_STOPPER\020\r\022\031\n\025SE"
  "G_DECELERATION_ZONE\020\016\022\020\n\014SEG_LANELINE\020\017\022"
  "\031\n\025SEG_FIRE_EXTINGUISHER\020\020\022\022\n\016SEG_BACKGR"
  "OUND\020\021\022\031\n\025SEG_GROUND_LOCK_CLOSE\020\022\022\020\n\013SEG"
  "_UNKNOWN\020\307\001*\303\003\n\024UltrObstacleCategory\022\031\n\024"
  "ULTRASONIC_FREESPACE\020\310\001\022\026\n\021ULTRASONIC_SQ"
  "UARE\020\311\001\022\026\n\021ULTRASONIC_CIRCLE\020\312\001\022\024\n\017ULTRA"
  "SONIC_EDGE\020\313\001\022\025\n\020ULTRASONIC_OTHER\020\314\001\022 \n\033"
  "ULTRASONIC_OTHER_AND_CIRCLE\020\315\001\022\036\n\031ULTRAS"
  "ONIC_DELAYED_CIRCLE\020\316\001\022\037\n\032ULTRASONIC_DIS"
  "TANCE_CIRCLE\020\317\001\022\'\n\"ULTRASONIC_DELAYED_DI"
  "STANCE_CIRCLE\020\320\001\022\035\n\030ULTRASONIC_CIRCLE_PE"
  "RSON\020\321\001\022%\n ULTRASONIC_DELAYED_CIRCLE_PER"
  "SON\020\322\001\022&\n!ULTRASONIC_LOW_CONF_CIRCLE_COM"
  "MON\020\323\001\022 \n\033ULTRASONIC_CIRCLE_AISLE_CAR\020\324\001"
  "\022\027\n\022ULTRASONIC_UNKNOWN\020\377\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_common_2eproto_deps[1] = {
  &::descriptor_table_geometry_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_common_2eproto_sccs[5] = {
  &scc_info_FusionObstacleCategory_common_2eproto.base,
  &scc_info_ObstacleObject_common_2eproto.base,
  &scc_info_ObstaclesAroundVehicle_common_2eproto.base,
  &scc_info_ParkingSlotLocation_common_2eproto.base,
  &scc_info_ParkingSlotPointsScore_common_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_common_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2eproto = {
  false, false, descriptor_table_protodef_common_2eproto, "common.proto", 1825,
  &descriptor_table_common_2eproto_once, descriptor_table_common_2eproto_sccs, descriptor_table_common_2eproto_deps, 5, 1,
  schemas, file_default_instances, TableStruct_common_2eproto::offsets,
  file_level_metadata_common_2eproto, 5, file_level_enum_descriptors_common_2eproto, file_level_service_descriptors_common_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_common_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_common_2eproto)), true);
namespace davinci_adas {
namespace apa {
namespace common {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ImageObstacleCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[0];
}
bool ImageObstacleCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 199:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UltrObstacleCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[1];
}
bool UltrObstacleCategory_IsValid(int value) {
  switch (value) {
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 207:
    case 208:
    case 209:
    case 210:
    case 211:
    case 212:
    case 255:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ParkingSlotPointsScore::_Internal {
 public:
  using HasBits = decltype(std::declval<ParkingSlotPointsScore>()._has_bits_);
  static void set_has_p0_score(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_p1_score(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_p2_score(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_p3_score(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

ParkingSlotPointsScore::ParkingSlotPointsScore(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:davinci_adas.apa.common.ParkingSlotPointsScore)
}
ParkingSlotPointsScore::ParkingSlotPointsScore(const ParkingSlotPointsScore& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&p0_score_, &from.p0_score_,
    static_cast<size_t>(reinterpret_cast<char*>(&p3_score_) -
    reinterpret_cast<char*>(&p0_score_)) + sizeof(p3_score_));
  // @@protoc_insertion_point(copy_constructor:davinci_adas.apa.common.ParkingSlotPointsScore)
}

void ParkingSlotPointsScore::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&p0_score_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&p3_score_) -
      reinterpret_cast<char*>(&p0_score_)) + sizeof(p3_score_));
}

ParkingSlotPointsScore::~ParkingSlotPointsScore() {
  // @@protoc_insertion_point(destructor:davinci_adas.apa.common.ParkingSlotPointsScore)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ParkingSlotPointsScore::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ParkingSlotPointsScore::ArenaDtor(void* object) {
  ParkingSlotPointsScore* _this = reinterpret_cast< ParkingSlotPointsScore* >(object);
  (void)_this;
}
void ParkingSlotPointsScore::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ParkingSlotPointsScore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ParkingSlotPointsScore& ParkingSlotPointsScore::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ParkingSlotPointsScore_common_2eproto.base);
  return *internal_default_instance();
}


void ParkingSlotPointsScore::Clear() {
// @@protoc_insertion_point(message_clear_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&p0_score_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&p3_score_) -
        reinterpret_cast<char*>(&p0_score_)) + sizeof(p3_score_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParkingSlotPointsScore::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional float p0_score = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          _Internal::set_has_p0_score(&has_bits);
          p0_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional float p1_score = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          _Internal::set_has_p1_score(&has_bits);
          p1_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional float p2_score = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          _Internal::set_has_p2_score(&has_bits);
          p2_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional float p3_score = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          _Internal::set_has_p3_score(&has_bits);
          p3_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ParkingSlotPointsScore::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional float p0_score = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_p0_score(), target);
  }

  // optional float p1_score = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_p1_score(), target);
  }

  // optional float p2_score = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_p2_score(), target);
  }

  // optional float p3_score = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_p3_score(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:davinci_adas.apa.common.ParkingSlotPointsScore)
  return target;
}

size_t ParkingSlotPointsScore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional float p0_score = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional float p1_score = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 4;
    }

    // optional float p2_score = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 4;
    }

    // optional float p3_score = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParkingSlotPointsScore::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  GOOGLE_DCHECK_NE(&from, this);
  const ParkingSlotPointsScore* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ParkingSlotPointsScore>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:davinci_adas.apa.common.ParkingSlotPointsScore)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:davinci_adas.apa.common.ParkingSlotPointsScore)
    MergeFrom(*source);
  }
}

void ParkingSlotPointsScore::MergeFrom(const ParkingSlotPointsScore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      p0_score_ = from.p0_score_;
    }
    if (cached_has_bits & 0x00000002u) {
      p1_score_ = from.p1_score_;
    }
    if (cached_has_bits & 0x00000004u) {
      p2_score_ = from.p2_score_;
    }
    if (cached_has_bits & 0x00000008u) {
      p3_score_ = from.p3_score_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParkingSlotPointsScore::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingSlotPointsScore::CopyFrom(const ParkingSlotPointsScore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:davinci_adas.apa.common.ParkingSlotPointsScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingSlotPointsScore::IsInitialized() const {
  return true;
}

void ParkingSlotPointsScore::InternalSwap(ParkingSlotPointsScore* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ParkingSlotPointsScore, p3_score_)
      + sizeof(ParkingSlotPointsScore::p3_score_)
      - PROTOBUF_FIELD_OFFSET(ParkingSlotPointsScore, p0_score_)>(
          reinterpret_cast<char*>(&p0_score_),
          reinterpret_cast<char*>(&other->p0_score_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ParkingSlotPointsScore::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ObstaclesAroundVehicle::_Internal {
 public:
  using HasBits = decltype(std::declval<ObstaclesAroundVehicle>()._has_bits_);
  static void set_has_front_free(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_left_free(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_right_free(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

ObstaclesAroundVehicle::ObstaclesAroundVehicle(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:davinci_adas.apa.common.ObstaclesAroundVehicle)
}
ObstaclesAroundVehicle::ObstaclesAroundVehicle(const ObstaclesAroundVehicle& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&front_free_, &from.front_free_,
    static_cast<size_t>(reinterpret_cast<char*>(&right_free_) -
    reinterpret_cast<char*>(&front_free_)) + sizeof(right_free_));
  // @@protoc_insertion_point(copy_constructor:davinci_adas.apa.common.ObstaclesAroundVehicle)
}

void ObstaclesAroundVehicle::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&front_free_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&right_free_) -
      reinterpret_cast<char*>(&front_free_)) + sizeof(right_free_));
}

ObstaclesAroundVehicle::~ObstaclesAroundVehicle() {
  // @@protoc_insertion_point(destructor:davinci_adas.apa.common.ObstaclesAroundVehicle)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ObstaclesAroundVehicle::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ObstaclesAroundVehicle::ArenaDtor(void* object) {
  ObstaclesAroundVehicle* _this = reinterpret_cast< ObstaclesAroundVehicle* >(object);
  (void)_this;
}
void ObstaclesAroundVehicle::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ObstaclesAroundVehicle::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ObstaclesAroundVehicle& ObstaclesAroundVehicle::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ObstaclesAroundVehicle_common_2eproto.base);
  return *internal_default_instance();
}


void ObstaclesAroundVehicle::Clear() {
// @@protoc_insertion_point(message_clear_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&front_free_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&right_free_) -
      reinterpret_cast<char*>(&front_free_)) + sizeof(right_free_));
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObstaclesAroundVehicle::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool front_free = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_front_free(&has_bits);
          front_free_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool left_free = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_left_free(&has_bits);
          left_free_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool right_free = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_right_free(&has_bits);
          right_free_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ObstaclesAroundVehicle::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool front_free = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_front_free(), target);
  }

  // optional bool left_free = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_left_free(), target);
  }

  // optional bool right_free = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_right_free(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:davinci_adas.apa.common.ObstaclesAroundVehicle)
  return target;
}

size_t ObstaclesAroundVehicle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bool front_free = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool left_free = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool right_free = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObstaclesAroundVehicle::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  GOOGLE_DCHECK_NE(&from, this);
  const ObstaclesAroundVehicle* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ObstaclesAroundVehicle>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:davinci_adas.apa.common.ObstaclesAroundVehicle)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:davinci_adas.apa.common.ObstaclesAroundVehicle)
    MergeFrom(*source);
  }
}

void ObstaclesAroundVehicle::MergeFrom(const ObstaclesAroundVehicle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      front_free_ = from.front_free_;
    }
    if (cached_has_bits & 0x00000002u) {
      left_free_ = from.left_free_;
    }
    if (cached_has_bits & 0x00000004u) {
      right_free_ = from.right_free_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ObstaclesAroundVehicle::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObstaclesAroundVehicle::CopyFrom(const ObstaclesAroundVehicle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:davinci_adas.apa.common.ObstaclesAroundVehicle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObstaclesAroundVehicle::IsInitialized() const {
  return true;
}

void ObstaclesAroundVehicle::InternalSwap(ObstaclesAroundVehicle* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObstaclesAroundVehicle, right_free_)
      + sizeof(ObstaclesAroundVehicle::right_free_)
      - PROTOBUF_FIELD_OFFSET(ObstaclesAroundVehicle, front_free_)>(
          reinterpret_cast<char*>(&front_free_),
          reinterpret_cast<char*>(&other->front_free_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObstaclesAroundVehicle::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ParkingSlotLocation::_Internal {
 public:
  using HasBits = decltype(std::declval<ParkingSlotLocation>()._has_bits_);
  static const ::davinci_adas::apa::geometry::Point2Df& p0(const ParkingSlotLocation* msg);
  static void set_has_p0(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::davinci_adas::apa::geometry::Point2Df& p1(const ParkingSlotLocation* msg);
  static void set_has_p1(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::davinci_adas::apa::geometry::Point2Df& p2(const ParkingSlotLocation* msg);
  static void set_has_p2(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::davinci_adas::apa::geometry::Point2Df& p3(const ParkingSlotLocation* msg);
  static void set_has_p3(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::davinci_adas::apa::geometry::Point2Df&
ParkingSlotLocation::_Internal::p0(const ParkingSlotLocation* msg) {
  return *msg->p0_;
}
const ::davinci_adas::apa::geometry::Point2Df&
ParkingSlotLocation::_Internal::p1(const ParkingSlotLocation* msg) {
  return *msg->p1_;
}
const ::davinci_adas::apa::geometry::Point2Df&
ParkingSlotLocation::_Internal::p2(const ParkingSlotLocation* msg) {
  return *msg->p2_;
}
const ::davinci_adas::apa::geometry::Point2Df&
ParkingSlotLocation::_Internal::p3(const ParkingSlotLocation* msg) {
  return *msg->p3_;
}
void ParkingSlotLocation::clear_p0() {
  if (p0_ != nullptr) p0_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void ParkingSlotLocation::clear_p1() {
  if (p1_ != nullptr) p1_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void ParkingSlotLocation::clear_p2() {
  if (p2_ != nullptr) p2_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
void ParkingSlotLocation::clear_p3() {
  if (p3_ != nullptr) p3_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
ParkingSlotLocation::ParkingSlotLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:davinci_adas.apa.common.ParkingSlotLocation)
}
ParkingSlotLocation::ParkingSlotLocation(const ParkingSlotLocation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_p0()) {
    p0_ = new ::davinci_adas::apa::geometry::Point2Df(*from.p0_);
  } else {
    p0_ = nullptr;
  }
  if (from._internal_has_p1()) {
    p1_ = new ::davinci_adas::apa::geometry::Point2Df(*from.p1_);
  } else {
    p1_ = nullptr;
  }
  if (from._internal_has_p2()) {
    p2_ = new ::davinci_adas::apa::geometry::Point2Df(*from.p2_);
  } else {
    p2_ = nullptr;
  }
  if (from._internal_has_p3()) {
    p3_ = new ::davinci_adas::apa::geometry::Point2Df(*from.p3_);
  } else {
    p3_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:davinci_adas.apa.common.ParkingSlotLocation)
}

void ParkingSlotLocation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ParkingSlotLocation_common_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&p0_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&p3_) -
      reinterpret_cast<char*>(&p0_)) + sizeof(p3_));
}

ParkingSlotLocation::~ParkingSlotLocation() {
  // @@protoc_insertion_point(destructor:davinci_adas.apa.common.ParkingSlotLocation)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ParkingSlotLocation::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete p0_;
  if (this != internal_default_instance()) delete p1_;
  if (this != internal_default_instance()) delete p2_;
  if (this != internal_default_instance()) delete p3_;
}

void ParkingSlotLocation::ArenaDtor(void* object) {
  ParkingSlotLocation* _this = reinterpret_cast< ParkingSlotLocation* >(object);
  (void)_this;
}
void ParkingSlotLocation::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ParkingSlotLocation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ParkingSlotLocation& ParkingSlotLocation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ParkingSlotLocation_common_2eproto.base);
  return *internal_default_instance();
}


void ParkingSlotLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:davinci_adas.apa.common.ParkingSlotLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(p0_ != nullptr);
      p0_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(p1_ != nullptr);
      p1_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(p2_ != nullptr);
      p2_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(p3_ != nullptr);
      p3_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParkingSlotLocation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .davinci_adas.apa.geometry.Point2Df p0 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_p0(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.geometry.Point2Df p1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_p1(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.geometry.Point2Df p2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_p2(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.geometry.Point2Df p3 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_p3(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ParkingSlotLocation::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:davinci_adas.apa.common.ParkingSlotLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .davinci_adas.apa.geometry.Point2Df p0 = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::p0(this), target, stream);
  }

  // optional .davinci_adas.apa.geometry.Point2Df p1 = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::p1(this), target, stream);
  }

  // optional .davinci_adas.apa.geometry.Point2Df p2 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::p2(this), target, stream);
  }

  // optional .davinci_adas.apa.geometry.Point2Df p3 = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::p3(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:davinci_adas.apa.common.ParkingSlotLocation)
  return target;
}

size_t ParkingSlotLocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:davinci_adas.apa.common.ParkingSlotLocation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .davinci_adas.apa.geometry.Point2Df p0 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *p0_);
    }

    // optional .davinci_adas.apa.geometry.Point2Df p1 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *p1_);
    }

    // optional .davinci_adas.apa.geometry.Point2Df p2 = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *p2_);
    }

    // optional .davinci_adas.apa.geometry.Point2Df p3 = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *p3_);
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParkingSlotLocation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:davinci_adas.apa.common.ParkingSlotLocation)
  GOOGLE_DCHECK_NE(&from, this);
  const ParkingSlotLocation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ParkingSlotLocation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:davinci_adas.apa.common.ParkingSlotLocation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:davinci_adas.apa.common.ParkingSlotLocation)
    MergeFrom(*source);
  }
}

void ParkingSlotLocation::MergeFrom(const ParkingSlotLocation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:davinci_adas.apa.common.ParkingSlotLocation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_p0()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_p0());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_p1()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_p1());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_p2()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_p2());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_mutable_p3()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_p3());
    }
  }
}

void ParkingSlotLocation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:davinci_adas.apa.common.ParkingSlotLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingSlotLocation::CopyFrom(const ParkingSlotLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:davinci_adas.apa.common.ParkingSlotLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingSlotLocation::IsInitialized() const {
  return true;
}

void ParkingSlotLocation::InternalSwap(ParkingSlotLocation* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ParkingSlotLocation, p3_)
      + sizeof(ParkingSlotLocation::p3_)
      - PROTOBUF_FIELD_OFFSET(ParkingSlotLocation, p0_)>(
          reinterpret_cast<char*>(&p0_),
          reinterpret_cast<char*>(&other->p0_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ParkingSlotLocation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class FusionObstacleCategory::_Internal {
 public:
  using HasBits = decltype(std::declval<FusionObstacleCategory>()._has_bits_);
  static void set_has_img_category(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_ultr_category(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

FusionObstacleCategory::FusionObstacleCategory(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:davinci_adas.apa.common.FusionObstacleCategory)
}
FusionObstacleCategory::FusionObstacleCategory(const FusionObstacleCategory& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&img_category_, &from.img_category_,
    static_cast<size_t>(reinterpret_cast<char*>(&ultr_category_) -
    reinterpret_cast<char*>(&img_category_)) + sizeof(ultr_category_));
  // @@protoc_insertion_point(copy_constructor:davinci_adas.apa.common.FusionObstacleCategory)
}

void FusionObstacleCategory::SharedCtor() {
  img_category_ = 0;
  ultr_category_ = 200;
}

FusionObstacleCategory::~FusionObstacleCategory() {
  // @@protoc_insertion_point(destructor:davinci_adas.apa.common.FusionObstacleCategory)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FusionObstacleCategory::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void FusionObstacleCategory::ArenaDtor(void* object) {
  FusionObstacleCategory* _this = reinterpret_cast< FusionObstacleCategory* >(object);
  (void)_this;
}
void FusionObstacleCategory::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FusionObstacleCategory::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FusionObstacleCategory& FusionObstacleCategory::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FusionObstacleCategory_common_2eproto.base);
  return *internal_default_instance();
}


void FusionObstacleCategory::Clear() {
// @@protoc_insertion_point(message_clear_start:davinci_adas.apa.common.FusionObstacleCategory)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    img_category_ = 0;
    ultr_category_ = 200;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FusionObstacleCategory::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .davinci_adas.apa.common.ImageObstacleCategory img_category = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::davinci_adas::apa::common::ImageObstacleCategory_IsValid(val))) {
            _internal_set_img_category(static_cast<::davinci_adas::apa::common::ImageObstacleCategory>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.common.UltrObstacleCategory ultr_category = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::davinci_adas::apa::common::UltrObstacleCategory_IsValid(val))) {
            _internal_set_ultr_category(static_cast<::davinci_adas::apa::common::UltrObstacleCategory>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FusionObstacleCategory::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:davinci_adas.apa.common.FusionObstacleCategory)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .davinci_adas.apa.common.ImageObstacleCategory img_category = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_img_category(), target);
  }

  // optional .davinci_adas.apa.common.UltrObstacleCategory ultr_category = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_ultr_category(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:davinci_adas.apa.common.FusionObstacleCategory)
  return target;
}

size_t FusionObstacleCategory::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:davinci_adas.apa.common.FusionObstacleCategory)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .davinci_adas.apa.common.ImageObstacleCategory img_category = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_img_category());
    }

    // optional .davinci_adas.apa.common.UltrObstacleCategory ultr_category = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_ultr_category());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FusionObstacleCategory::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:davinci_adas.apa.common.FusionObstacleCategory)
  GOOGLE_DCHECK_NE(&from, this);
  const FusionObstacleCategory* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FusionObstacleCategory>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:davinci_adas.apa.common.FusionObstacleCategory)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:davinci_adas.apa.common.FusionObstacleCategory)
    MergeFrom(*source);
  }
}

void FusionObstacleCategory::MergeFrom(const FusionObstacleCategory& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:davinci_adas.apa.common.FusionObstacleCategory)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      img_category_ = from.img_category_;
    }
    if (cached_has_bits & 0x00000002u) {
      ultr_category_ = from.ultr_category_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void FusionObstacleCategory::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:davinci_adas.apa.common.FusionObstacleCategory)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FusionObstacleCategory::CopyFrom(const FusionObstacleCategory& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:davinci_adas.apa.common.FusionObstacleCategory)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FusionObstacleCategory::IsInitialized() const {
  return true;
}

void FusionObstacleCategory::InternalSwap(FusionObstacleCategory* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(img_category_, other->img_category_);
  swap(ultr_category_, other->ultr_category_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FusionObstacleCategory::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ObstacleObject::_Internal {
 public:
  using HasBits = decltype(std::declval<ObstacleObject>()._has_bits_);
  static void set_has_obs_id(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_obs_score(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::davinci_adas::apa::common::FusionObstacleCategory& obs_tag(const ObstacleObject* msg);
  static void set_has_obs_tag(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::davinci_adas::apa::geometry::Point2Df& obs_closest_point(const ObstacleObject* msg);
  static void set_has_obs_closest_point(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::davinci_adas::apa::geometry::Point2Df& obs_velocity(const ObstacleObject* msg);
  static void set_has_obs_velocity(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::davinci_adas::apa::common::FusionObstacleCategory&
ObstacleObject::_Internal::obs_tag(const ObstacleObject* msg) {
  return *msg->obs_tag_;
}
const ::davinci_adas::apa::geometry::Point2Df&
ObstacleObject::_Internal::obs_closest_point(const ObstacleObject* msg) {
  return *msg->obs_closest_point_;
}
const ::davinci_adas::apa::geometry::Point2Df&
ObstacleObject::_Internal::obs_velocity(const ObstacleObject* msg) {
  return *msg->obs_velocity_;
}
void ObstacleObject::clear_obs_closest_point() {
  if (obs_closest_point_ != nullptr) obs_closest_point_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void ObstacleObject::clear_obs_velocity() {
  if (obs_velocity_ != nullptr) obs_velocity_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
void ObstacleObject::clear_obs_points() {
  obs_points_.Clear();
}
ObstacleObject::ObstacleObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  obs_points_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:davinci_adas.apa.common.ObstacleObject)
}
ObstacleObject::ObstacleObject(const ObstacleObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      obs_points_(from.obs_points_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_obs_tag()) {
    obs_tag_ = new ::davinci_adas::apa::common::FusionObstacleCategory(*from.obs_tag_);
  } else {
    obs_tag_ = nullptr;
  }
  if (from._internal_has_obs_closest_point()) {
    obs_closest_point_ = new ::davinci_adas::apa::geometry::Point2Df(*from.obs_closest_point_);
  } else {
    obs_closest_point_ = nullptr;
  }
  if (from._internal_has_obs_velocity()) {
    obs_velocity_ = new ::davinci_adas::apa::geometry::Point2Df(*from.obs_velocity_);
  } else {
    obs_velocity_ = nullptr;
  }
  ::memcpy(&obs_id_, &from.obs_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&obs_score_) -
    reinterpret_cast<char*>(&obs_id_)) + sizeof(obs_score_));
  // @@protoc_insertion_point(copy_constructor:davinci_adas.apa.common.ObstacleObject)
}

void ObstacleObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ObstacleObject_common_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&obs_tag_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&obs_score_) -
      reinterpret_cast<char*>(&obs_tag_)) + sizeof(obs_score_));
}

ObstacleObject::~ObstacleObject() {
  // @@protoc_insertion_point(destructor:davinci_adas.apa.common.ObstacleObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ObstacleObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete obs_tag_;
  if (this != internal_default_instance()) delete obs_closest_point_;
  if (this != internal_default_instance()) delete obs_velocity_;
}

void ObstacleObject::ArenaDtor(void* object) {
  ObstacleObject* _this = reinterpret_cast< ObstacleObject* >(object);
  (void)_this;
}
void ObstacleObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ObstacleObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ObstacleObject& ObstacleObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ObstacleObject_common_2eproto.base);
  return *internal_default_instance();
}


void ObstacleObject::Clear() {
// @@protoc_insertion_point(message_clear_start:davinci_adas.apa.common.ObstacleObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  obs_points_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(obs_tag_ != nullptr);
      obs_tag_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(obs_closest_point_ != nullptr);
      obs_closest_point_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(obs_velocity_ != nullptr);
      obs_velocity_->Clear();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&obs_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&obs_score_) -
        reinterpret_cast<char*>(&obs_id_)) + sizeof(obs_score_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObstacleObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional uint32 obs_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_obs_id(&has_bits);
          obs_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional float obs_score = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          _Internal::set_has_obs_score(&has_bits);
          obs_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.common.FusionObstacleCategory obs_tag = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_obs_tag(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.geometry.Point2Df obs_closest_point = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_obs_closest_point(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .davinci_adas.apa.geometry.Point2Df obs_velocity = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_obs_velocity(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .davinci_adas.apa.geometry.Point2Df obs_points = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_obs_points(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ObstacleObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:davinci_adas.apa.common.ObstacleObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 obs_id = 1;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_obs_id(), target);
  }

  // optional float obs_score = 2;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_obs_score(), target);
  }

  // optional .davinci_adas.apa.common.FusionObstacleCategory obs_tag = 3;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::obs_tag(this), target, stream);
  }

  // optional .davinci_adas.apa.geometry.Point2Df obs_closest_point = 4;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::obs_closest_point(this), target, stream);
  }

  // optional .davinci_adas.apa.geometry.Point2Df obs_velocity = 5;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::obs_velocity(this), target, stream);
  }

  // repeated .davinci_adas.apa.geometry.Point2Df obs_points = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_obs_points_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_obs_points(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:davinci_adas.apa.common.ObstacleObject)
  return target;
}

size_t ObstacleObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:davinci_adas.apa.common.ObstacleObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .davinci_adas.apa.geometry.Point2Df obs_points = 6;
  total_size += 1UL * this->_internal_obs_points_size();
  for (const auto& msg : this->obs_points_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional .davinci_adas.apa.common.FusionObstacleCategory obs_tag = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *obs_tag_);
    }

    // optional .davinci_adas.apa.geometry.Point2Df obs_closest_point = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *obs_closest_point_);
    }

    // optional .davinci_adas.apa.geometry.Point2Df obs_velocity = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *obs_velocity_);
    }

    // optional uint32 obs_id = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_obs_id());
    }

    // optional float obs_score = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObstacleObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:davinci_adas.apa.common.ObstacleObject)
  GOOGLE_DCHECK_NE(&from, this);
  const ObstacleObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ObstacleObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:davinci_adas.apa.common.ObstacleObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:davinci_adas.apa.common.ObstacleObject)
    MergeFrom(*source);
  }
}

void ObstacleObject::MergeFrom(const ObstacleObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:davinci_adas.apa.common.ObstacleObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  obs_points_.MergeFrom(from.obs_points_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_obs_tag()->::davinci_adas::apa::common::FusionObstacleCategory::MergeFrom(from._internal_obs_tag());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_obs_closest_point()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_obs_closest_point());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_obs_velocity()->::davinci_adas::apa::geometry::Point2Df::MergeFrom(from._internal_obs_velocity());
    }
    if (cached_has_bits & 0x00000008u) {
      obs_id_ = from.obs_id_;
    }
    if (cached_has_bits & 0x00000010u) {
      obs_score_ = from.obs_score_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ObstacleObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:davinci_adas.apa.common.ObstacleObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObstacleObject::CopyFrom(const ObstacleObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:davinci_adas.apa.common.ObstacleObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObstacleObject::IsInitialized() const {
  return true;
}

void ObstacleObject::InternalSwap(ObstacleObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  obs_points_.InternalSwap(&other->obs_points_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObstacleObject, obs_score_)
      + sizeof(ObstacleObject::obs_score_)
      - PROTOBUF_FIELD_OFFSET(ObstacleObject, obs_tag_)>(
          reinterpret_cast<char*>(&obs_tag_),
          reinterpret_cast<char*>(&other->obs_tag_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObstacleObject::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace apa
}  // namespace davinci_adas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::davinci_adas::apa::common::ParkingSlotPointsScore* Arena::CreateMaybeMessage< ::davinci_adas::apa::common::ParkingSlotPointsScore >(Arena* arena) {
  return Arena::CreateMessageInternal< ::davinci_adas::apa::common::ParkingSlotPointsScore >(arena);
}
template<> PROTOBUF_NOINLINE ::davinci_adas::apa::common::ObstaclesAroundVehicle* Arena::CreateMaybeMessage< ::davinci_adas::apa::common::ObstaclesAroundVehicle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::davinci_adas::apa::common::ObstaclesAroundVehicle >(arena);
}
template<> PROTOBUF_NOINLINE ::davinci_adas::apa::common::ParkingSlotLocation* Arena::CreateMaybeMessage< ::davinci_adas::apa::common::ParkingSlotLocation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::davinci_adas::apa::common::ParkingSlotLocation >(arena);
}
template<> PROTOBUF_NOINLINE ::davinci_adas::apa::common::FusionObstacleCategory* Arena::CreateMaybeMessage< ::davinci_adas::apa::common::FusionObstacleCategory >(Arena* arena) {
  return Arena::CreateMessageInternal< ::davinci_adas::apa::common::FusionObstacleCategory >(arena);
}
template<> PROTOBUF_NOINLINE ::davinci_adas::apa::common::ObstacleObject* Arena::CreateMaybeMessage< ::davinci_adas::apa::common::ObstacleObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::davinci_adas::apa::common::ObstacleObject >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
