// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geometry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_geometry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_geometry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_geometry_2eproto;
namespace davinci_adas {
namespace apa {
namespace geometry {
class Line;
class LineDefaultTypeInternal;
extern LineDefaultTypeInternal _Line_default_instance_;
class Point2Df;
class Point2DfDefaultTypeInternal;
extern Point2DfDefaultTypeInternal _Point2Df_default_instance_;
class Polygon;
class PolygonDefaultTypeInternal;
extern PolygonDefaultTypeInternal _Polygon_default_instance_;
class Pose;
class PoseDefaultTypeInternal;
extern PoseDefaultTypeInternal _Pose_default_instance_;
}  // namespace geometry
}  // namespace apa
}  // namespace davinci_adas
PROTOBUF_NAMESPACE_OPEN
template<> ::davinci_adas::apa::geometry::Line* Arena::CreateMaybeMessage<::davinci_adas::apa::geometry::Line>(Arena*);
template<> ::davinci_adas::apa::geometry::Point2Df* Arena::CreateMaybeMessage<::davinci_adas::apa::geometry::Point2Df>(Arena*);
template<> ::davinci_adas::apa::geometry::Polygon* Arena::CreateMaybeMessage<::davinci_adas::apa::geometry::Polygon>(Arena*);
template<> ::davinci_adas::apa::geometry::Pose* Arena::CreateMaybeMessage<::davinci_adas::apa::geometry::Pose>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace davinci_adas {
namespace apa {
namespace geometry {

// ===================================================================

class Point2Df PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:davinci_adas.apa.geometry.Point2Df) */ {
 public:
  inline Point2Df() : Point2Df(nullptr) {}
  virtual ~Point2Df();

  Point2Df(const Point2Df& from);
  Point2Df(Point2Df&& from) noexcept
    : Point2Df() {
    *this = ::std::move(from);
  }

  inline Point2Df& operator=(const Point2Df& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point2Df& operator=(Point2Df&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point2Df& default_instance();

  static inline const Point2Df* internal_default_instance() {
    return reinterpret_cast<const Point2Df*>(
               &_Point2Df_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point2Df& a, Point2Df& b) {
    a.Swap(&b);
  }
  inline void Swap(Point2Df* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point2Df* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point2Df* New() const final {
    return CreateMaybeMessage<Point2Df>(nullptr);
  }

  Point2Df* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point2Df>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point2Df& from);
  void MergeFrom(const Point2Df& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point2Df* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "davinci_adas.apa.geometry.Point2Df";
  }
  protected:
  explicit Point2Df(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kCovXxFieldNumber = 3,
    kCovYyFieldNumber = 4,
  };
  // optional float x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // optional float y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // optional float cov_xx = 3;
  bool has_cov_xx() const;
  private:
  bool _internal_has_cov_xx() const;
  public:
  void clear_cov_xx();
  float cov_xx() const;
  void set_cov_xx(float value);
  private:
  float _internal_cov_xx() const;
  void _internal_set_cov_xx(float value);
  public:

  // optional float cov_yy = 4;
  bool has_cov_yy() const;
  private:
  bool _internal_has_cov_yy() const;
  public:
  void clear_cov_yy();
  float cov_yy() const;
  void set_cov_yy(float value);
  private:
  float _internal_cov_yy() const;
  void _internal_set_cov_yy(float value);
  public:

  // @@protoc_insertion_point(class_scope:davinci_adas.apa.geometry.Point2Df)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float x_;
  float y_;
  float cov_xx_;
  float cov_yy_;
  friend struct ::TableStruct_geometry_2eproto;
};
// -------------------------------------------------------------------

class Pose PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:davinci_adas.apa.geometry.Pose) */ {
 public:
  inline Pose() : Pose(nullptr) {}
  virtual ~Pose();

  Pose(const Pose& from);
  Pose(Pose&& from) noexcept
    : Pose() {
    *this = ::std::move(from);
  }

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }
  inline Pose& operator=(Pose&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Pose& default_instance();

  static inline const Pose* internal_default_instance() {
    return reinterpret_cast<const Pose*>(
               &_Pose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Pose& a, Pose& b) {
    a.Swap(&b);
  }
  inline void Swap(Pose* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Pose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Pose* New() const final {
    return CreateMaybeMessage<Pose>(nullptr);
  }

  Pose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Pose>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Pose* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "davinci_adas.apa.geometry.Pose";
  }
  protected:
  explicit Pose(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kYawFieldNumber = 3,
  };
  // optional double x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // optional double y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // optional double yaw = 3;
  bool has_yaw() const;
  private:
  bool _internal_has_yaw() const;
  public:
  void clear_yaw();
  double yaw() const;
  void set_yaw(double value);
  private:
  double _internal_yaw() const;
  void _internal_set_yaw(double value);
  public:

  // @@protoc_insertion_point(class_scope:davinci_adas.apa.geometry.Pose)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double x_;
  double y_;
  double yaw_;
  friend struct ::TableStruct_geometry_2eproto;
};
// -------------------------------------------------------------------

class Line PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:davinci_adas.apa.geometry.Line) */ {
 public:
  inline Line() : Line(nullptr) {}
  virtual ~Line();

  Line(const Line& from);
  Line(Line&& from) noexcept
    : Line() {
    *this = ::std::move(from);
  }

  inline Line& operator=(const Line& from) {
    CopyFrom(from);
    return *this;
  }
  inline Line& operator=(Line&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Line& default_instance();

  static inline const Line* internal_default_instance() {
    return reinterpret_cast<const Line*>(
               &_Line_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Line& a, Line& b) {
    a.Swap(&b);
  }
  inline void Swap(Line* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Line* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Line* New() const final {
    return CreateMaybeMessage<Line>(nullptr);
  }

  Line* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Line>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Line& from);
  void MergeFrom(const Line& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Line* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "davinci_adas.apa.geometry.Line";
  }
  protected:
  explicit Line(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartFieldNumber = 1,
    kEndFieldNumber = 2,
  };
  // optional .davinci_adas.apa.geometry.Point2Df start = 1;
  bool has_start() const;
  private:
  bool _internal_has_start() const;
  public:
  void clear_start();
  const ::davinci_adas::apa::geometry::Point2Df& start() const;
  ::davinci_adas::apa::geometry::Point2Df* release_start();
  ::davinci_adas::apa::geometry::Point2Df* mutable_start();
  void set_allocated_start(::davinci_adas::apa::geometry::Point2Df* start);
  private:
  const ::davinci_adas::apa::geometry::Point2Df& _internal_start() const;
  ::davinci_adas::apa::geometry::Point2Df* _internal_mutable_start();
  public:
  void unsafe_arena_set_allocated_start(
      ::davinci_adas::apa::geometry::Point2Df* start);
  ::davinci_adas::apa::geometry::Point2Df* unsafe_arena_release_start();

  // optional .davinci_adas.apa.geometry.Point2Df end = 2;
  bool has_end() const;
  private:
  bool _internal_has_end() const;
  public:
  void clear_end();
  const ::davinci_adas::apa::geometry::Point2Df& end() const;
  ::davinci_adas::apa::geometry::Point2Df* release_end();
  ::davinci_adas::apa::geometry::Point2Df* mutable_end();
  void set_allocated_end(::davinci_adas::apa::geometry::Point2Df* end);
  private:
  const ::davinci_adas::apa::geometry::Point2Df& _internal_end() const;
  ::davinci_adas::apa::geometry::Point2Df* _internal_mutable_end();
  public:
  void unsafe_arena_set_allocated_end(
      ::davinci_adas::apa::geometry::Point2Df* end);
  ::davinci_adas::apa::geometry::Point2Df* unsafe_arena_release_end();

  // @@protoc_insertion_point(class_scope:davinci_adas.apa.geometry.Line)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::davinci_adas::apa::geometry::Point2Df* start_;
  ::davinci_adas::apa::geometry::Point2Df* end_;
  friend struct ::TableStruct_geometry_2eproto;
};
// -------------------------------------------------------------------

class Polygon PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:davinci_adas.apa.geometry.Polygon) */ {
 public:
  inline Polygon() : Polygon(nullptr) {}
  virtual ~Polygon();

  Polygon(const Polygon& from);
  Polygon(Polygon&& from) noexcept
    : Polygon() {
    *this = ::std::move(from);
  }

  inline Polygon& operator=(const Polygon& from) {
    CopyFrom(from);
    return *this;
  }
  inline Polygon& operator=(Polygon&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Polygon& default_instance();

  static inline const Polygon* internal_default_instance() {
    return reinterpret_cast<const Polygon*>(
               &_Polygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Polygon& a, Polygon& b) {
    a.Swap(&b);
  }
  inline void Swap(Polygon* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Polygon* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Polygon* New() const final {
    return CreateMaybeMessage<Polygon>(nullptr);
  }

  Polygon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Polygon>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Polygon& from);
  void MergeFrom(const Polygon& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Polygon* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "davinci_adas.apa.geometry.Polygon";
  }
  protected:
  explicit Polygon(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 2,
    kIsOpenFieldNumber = 1,
  };
  // repeated .davinci_adas.apa.geometry.Point2Df points = 2;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::davinci_adas::apa::geometry::Point2Df* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::davinci_adas::apa::geometry::Point2Df >*
      mutable_points();
  private:
  const ::davinci_adas::apa::geometry::Point2Df& _internal_points(int index) const;
  ::davinci_adas::apa::geometry::Point2Df* _internal_add_points();
  public:
  const ::davinci_adas::apa::geometry::Point2Df& points(int index) const;
  ::davinci_adas::apa::geometry::Point2Df* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::davinci_adas::apa::geometry::Point2Df >&
      points() const;

  // optional bool is_open = 1;
  bool has_is_open() const;
  private:
  bool _internal_has_is_open() const;
  public:
  void clear_is_open();
  bool is_open() const;
  void set_is_open(bool value);
  private:
  bool _internal_is_open() const;
  void _internal_set_is_open(bool value);
  public:

  // @@protoc_insertion_point(class_scope:davinci_adas.apa.geometry.Polygon)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::davinci_adas::apa::geometry::Point2Df > points_;
  bool is_open_;
  friend struct ::TableStruct_geometry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point2Df

// optional float x = 1;
inline bool Point2Df::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Point2Df::has_x() const {
  return _internal_has_x();
}
inline void Point2Df::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float Point2Df::_internal_x() const {
  return x_;
}
inline float Point2Df::x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Point2Df.x)
  return _internal_x();
}
inline void Point2Df::_internal_set_x(float value) {
  _has_bits_[0] |= 0x00000001u;
  x_ = value;
}
inline void Point2Df::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Point2Df.x)
}

// optional float y = 2;
inline bool Point2Df::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Point2Df::has_y() const {
  return _internal_has_y();
}
inline void Point2Df::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float Point2Df::_internal_y() const {
  return y_;
}
inline float Point2Df::y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Point2Df.y)
  return _internal_y();
}
inline void Point2Df::_internal_set_y(float value) {
  _has_bits_[0] |= 0x00000002u;
  y_ = value;
}
inline void Point2Df::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Point2Df.y)
}

// optional float cov_xx = 3;
inline bool Point2Df::_internal_has_cov_xx() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Point2Df::has_cov_xx() const {
  return _internal_has_cov_xx();
}
inline void Point2Df::clear_cov_xx() {
  cov_xx_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float Point2Df::_internal_cov_xx() const {
  return cov_xx_;
}
inline float Point2Df::cov_xx() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Point2Df.cov_xx)
  return _internal_cov_xx();
}
inline void Point2Df::_internal_set_cov_xx(float value) {
  _has_bits_[0] |= 0x00000004u;
  cov_xx_ = value;
}
inline void Point2Df::set_cov_xx(float value) {
  _internal_set_cov_xx(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Point2Df.cov_xx)
}

// optional float cov_yy = 4;
inline bool Point2Df::_internal_has_cov_yy() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Point2Df::has_cov_yy() const {
  return _internal_has_cov_yy();
}
inline void Point2Df::clear_cov_yy() {
  cov_yy_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float Point2Df::_internal_cov_yy() const {
  return cov_yy_;
}
inline float Point2Df::cov_yy() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Point2Df.cov_yy)
  return _internal_cov_yy();
}
inline void Point2Df::_internal_set_cov_yy(float value) {
  _has_bits_[0] |= 0x00000008u;
  cov_yy_ = value;
}
inline void Point2Df::set_cov_yy(float value) {
  _internal_set_cov_yy(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Point2Df.cov_yy)
}

// -------------------------------------------------------------------

// Pose

// optional double x = 1;
inline bool Pose::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Pose::has_x() const {
  return _internal_has_x();
}
inline void Pose::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Pose::_internal_x() const {
  return x_;
}
inline double Pose::x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Pose.x)
  return _internal_x();
}
inline void Pose::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000001u;
  x_ = value;
}
inline void Pose::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Pose.x)
}

// optional double y = 2;
inline bool Pose::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Pose::has_y() const {
  return _internal_has_y();
}
inline void Pose::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Pose::_internal_y() const {
  return y_;
}
inline double Pose::y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Pose.y)
  return _internal_y();
}
inline void Pose::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000002u;
  y_ = value;
}
inline void Pose::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Pose.y)
}

// optional double yaw = 3;
inline bool Pose::_internal_has_yaw() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Pose::has_yaw() const {
  return _internal_has_yaw();
}
inline void Pose::clear_yaw() {
  yaw_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Pose::_internal_yaw() const {
  return yaw_;
}
inline double Pose::yaw() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Pose.yaw)
  return _internal_yaw();
}
inline void Pose::_internal_set_yaw(double value) {
  _has_bits_[0] |= 0x00000004u;
  yaw_ = value;
}
inline void Pose::set_yaw(double value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Pose.yaw)
}

// -------------------------------------------------------------------

// Line

// optional .davinci_adas.apa.geometry.Point2Df start = 1;
inline bool Line::_internal_has_start() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || start_ != nullptr);
  return value;
}
inline bool Line::has_start() const {
  return _internal_has_start();
}
inline void Line::clear_start() {
  if (start_ != nullptr) start_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::davinci_adas::apa::geometry::Point2Df& Line::_internal_start() const {
  const ::davinci_adas::apa::geometry::Point2Df* p = start_;
  return p != nullptr ? *p : reinterpret_cast<const ::davinci_adas::apa::geometry::Point2Df&>(
      ::davinci_adas::apa::geometry::_Point2Df_default_instance_);
}
inline const ::davinci_adas::apa::geometry::Point2Df& Line::start() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Line.start)
  return _internal_start();
}
inline void Line::unsafe_arena_set_allocated_start(
    ::davinci_adas::apa::geometry::Point2Df* start) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(start_);
  }
  start_ = start;
  if (start) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:davinci_adas.apa.geometry.Line.start)
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::release_start() {
  _has_bits_[0] &= ~0x00000001u;
  ::davinci_adas::apa::geometry::Point2Df* temp = start_;
  start_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::unsafe_arena_release_start() {
  // @@protoc_insertion_point(field_release:davinci_adas.apa.geometry.Line.start)
  _has_bits_[0] &= ~0x00000001u;
  ::davinci_adas::apa::geometry::Point2Df* temp = start_;
  start_ = nullptr;
  return temp;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::_internal_mutable_start() {
  _has_bits_[0] |= 0x00000001u;
  if (start_ == nullptr) {
    auto* p = CreateMaybeMessage<::davinci_adas::apa::geometry::Point2Df>(GetArena());
    start_ = p;
  }
  return start_;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::mutable_start() {
  // @@protoc_insertion_point(field_mutable:davinci_adas.apa.geometry.Line.start)
  return _internal_mutable_start();
}
inline void Line::set_allocated_start(::davinci_adas::apa::geometry::Point2Df* start) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete start_;
  }
  if (start) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(start);
    if (message_arena != submessage_arena) {
      start = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, start, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  start_ = start;
  // @@protoc_insertion_point(field_set_allocated:davinci_adas.apa.geometry.Line.start)
}

// optional .davinci_adas.apa.geometry.Point2Df end = 2;
inline bool Line::_internal_has_end() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || end_ != nullptr);
  return value;
}
inline bool Line::has_end() const {
  return _internal_has_end();
}
inline void Line::clear_end() {
  if (end_ != nullptr) end_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::davinci_adas::apa::geometry::Point2Df& Line::_internal_end() const {
  const ::davinci_adas::apa::geometry::Point2Df* p = end_;
  return p != nullptr ? *p : reinterpret_cast<const ::davinci_adas::apa::geometry::Point2Df&>(
      ::davinci_adas::apa::geometry::_Point2Df_default_instance_);
}
inline const ::davinci_adas::apa::geometry::Point2Df& Line::end() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Line.end)
  return _internal_end();
}
inline void Line::unsafe_arena_set_allocated_end(
    ::davinci_adas::apa::geometry::Point2Df* end) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(end_);
  }
  end_ = end;
  if (end) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:davinci_adas.apa.geometry.Line.end)
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::release_end() {
  _has_bits_[0] &= ~0x00000002u;
  ::davinci_adas::apa::geometry::Point2Df* temp = end_;
  end_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::unsafe_arena_release_end() {
  // @@protoc_insertion_point(field_release:davinci_adas.apa.geometry.Line.end)
  _has_bits_[0] &= ~0x00000002u;
  ::davinci_adas::apa::geometry::Point2Df* temp = end_;
  end_ = nullptr;
  return temp;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::_internal_mutable_end() {
  _has_bits_[0] |= 0x00000002u;
  if (end_ == nullptr) {
    auto* p = CreateMaybeMessage<::davinci_adas::apa::geometry::Point2Df>(GetArena());
    end_ = p;
  }
  return end_;
}
inline ::davinci_adas::apa::geometry::Point2Df* Line::mutable_end() {
  // @@protoc_insertion_point(field_mutable:davinci_adas.apa.geometry.Line.end)
  return _internal_mutable_end();
}
inline void Line::set_allocated_end(::davinci_adas::apa::geometry::Point2Df* end) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete end_;
  }
  if (end) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(end);
    if (message_arena != submessage_arena) {
      end = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, end, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  end_ = end;
  // @@protoc_insertion_point(field_set_allocated:davinci_adas.apa.geometry.Line.end)
}

// -------------------------------------------------------------------

// Polygon

// optional bool is_open = 1;
inline bool Polygon::_internal_has_is_open() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Polygon::has_is_open() const {
  return _internal_has_is_open();
}
inline void Polygon::clear_is_open() {
  is_open_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool Polygon::_internal_is_open() const {
  return is_open_;
}
inline bool Polygon::is_open() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Polygon.is_open)
  return _internal_is_open();
}
inline void Polygon::_internal_set_is_open(bool value) {
  _has_bits_[0] |= 0x00000001u;
  is_open_ = value;
}
inline void Polygon::set_is_open(bool value) {
  _internal_set_is_open(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.geometry.Polygon.is_open)
}

// repeated .davinci_adas.apa.geometry.Point2Df points = 2;
inline int Polygon::_internal_points_size() const {
  return points_.size();
}
inline int Polygon::points_size() const {
  return _internal_points_size();
}
inline void Polygon::clear_points() {
  points_.Clear();
}
inline ::davinci_adas::apa::geometry::Point2Df* Polygon::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:davinci_adas.apa.geometry.Polygon.points)
  return points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::davinci_adas::apa::geometry::Point2Df >*
Polygon::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:davinci_adas.apa.geometry.Polygon.points)
  return &points_;
}
inline const ::davinci_adas::apa::geometry::Point2Df& Polygon::_internal_points(int index) const {
  return points_.Get(index);
}
inline const ::davinci_adas::apa::geometry::Point2Df& Polygon::points(int index) const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.geometry.Polygon.points)
  return _internal_points(index);
}
inline ::davinci_adas::apa::geometry::Point2Df* Polygon::_internal_add_points() {
  return points_.Add();
}
inline ::davinci_adas::apa::geometry::Point2Df* Polygon::add_points() {
  // @@protoc_insertion_point(field_add:davinci_adas.apa.geometry.Polygon.points)
  return _internal_add_points();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::davinci_adas::apa::geometry::Point2Df >&
Polygon::points() const {
  // @@protoc_insertion_point(field_list:davinci_adas.apa.geometry.Polygon.points)
  return points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace geometry
}  // namespace apa
}  // namespace davinci_adas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto
