// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odometry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_odometry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_odometry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_odometry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_odometry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_odometry_2eproto;
namespace davinci_adas {
namespace apa {
namespace odometry {
class Odometry;
class OdometryDefaultTypeInternal;
extern OdometryDefaultTypeInternal _Odometry_default_instance_;
}  // namespace odometry
}  // namespace apa
}  // namespace davinci_adas
PROTOBUF_NAMESPACE_OPEN
template<> ::davinci_adas::apa::odometry::Odometry* Arena::CreateMaybeMessage<::davinci_adas::apa::odometry::Odometry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace davinci_adas {
namespace apa {
namespace odometry {

// ===================================================================

class Odometry PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:davinci_adas.apa.odometry.Odometry) */ {
 public:
  inline Odometry() : Odometry(nullptr) {}
  virtual ~Odometry();

  Odometry(const Odometry& from);
  Odometry(Odometry&& from) noexcept
    : Odometry() {
    *this = ::std::move(from);
  }

  inline Odometry& operator=(const Odometry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Odometry& operator=(Odometry&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Odometry& default_instance();

  static inline const Odometry* internal_default_instance() {
    return reinterpret_cast<const Odometry*>(
               &_Odometry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Odometry& a, Odometry& b) {
    a.Swap(&b);
  }
  inline void Swap(Odometry* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Odometry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Odometry* New() const final {
    return CreateMaybeMessage<Odometry>(nullptr);
  }

  Odometry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Odometry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Odometry& from);
  void MergeFrom(const Odometry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Odometry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "davinci_adas.apa.odometry.Odometry";
  }
  protected:
  explicit Odometry(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_odometry_2eproto);
    return ::descriptor_table_odometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
    kPitchFieldNumber = 5,
    kRollFieldNumber = 6,
    kYawFieldNumber = 7,
    kVelocityXFieldNumber = 8,
    kVelocityYFieldNumber = 9,
    kVelocityZFieldNumber = 10,
    kAccelerationXFieldNumber = 11,
    kAccelerationYFieldNumber = 12,
    kAccelerationZFieldNumber = 13,
    kAngleVelXFieldNumber = 14,
    kAngleVelYFieldNumber = 15,
    kAngleVelZFieldNumber = 16,
    kOdometryFunctionFieldNumber = 17,
    kErrorCodeFieldNumber = 18,
    kXWheelOdomFieldNumber = 19,
    kYWheelOdomFieldNumber = 20,
    kYawWheelOdomFieldNumber = 21,
  };
  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);
  private:
  const ::apollo::common::Header& _internal_header() const;
  ::apollo::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::apollo::common::Header* header);
  ::apollo::common::Header* unsafe_arena_release_header();

  // optional float x = 2;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // optional float y = 3;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // optional float z = 4;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // optional float pitch = 5;
  bool has_pitch() const;
  private:
  bool _internal_has_pitch() const;
  public:
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // optional float roll = 6;
  bool has_roll() const;
  private:
  bool _internal_has_roll() const;
  public:
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // optional float yaw = 7;
  bool has_yaw() const;
  private:
  bool _internal_has_yaw() const;
  public:
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // optional float velocity_x = 8;
  bool has_velocity_x() const;
  private:
  bool _internal_has_velocity_x() const;
  public:
  void clear_velocity_x();
  float velocity_x() const;
  void set_velocity_x(float value);
  private:
  float _internal_velocity_x() const;
  void _internal_set_velocity_x(float value);
  public:

  // optional float velocity_y = 9;
  bool has_velocity_y() const;
  private:
  bool _internal_has_velocity_y() const;
  public:
  void clear_velocity_y();
  float velocity_y() const;
  void set_velocity_y(float value);
  private:
  float _internal_velocity_y() const;
  void _internal_set_velocity_y(float value);
  public:

  // optional float velocity_z = 10;
  bool has_velocity_z() const;
  private:
  bool _internal_has_velocity_z() const;
  public:
  void clear_velocity_z();
  float velocity_z() const;
  void set_velocity_z(float value);
  private:
  float _internal_velocity_z() const;
  void _internal_set_velocity_z(float value);
  public:

  // optional float acceleration_x = 11;
  bool has_acceleration_x() const;
  private:
  bool _internal_has_acceleration_x() const;
  public:
  void clear_acceleration_x();
  float acceleration_x() const;
  void set_acceleration_x(float value);
  private:
  float _internal_acceleration_x() const;
  void _internal_set_acceleration_x(float value);
  public:

  // optional float acceleration_y = 12;
  bool has_acceleration_y() const;
  private:
  bool _internal_has_acceleration_y() const;
  public:
  void clear_acceleration_y();
  float acceleration_y() const;
  void set_acceleration_y(float value);
  private:
  float _internal_acceleration_y() const;
  void _internal_set_acceleration_y(float value);
  public:

  // optional float acceleration_z = 13;
  bool has_acceleration_z() const;
  private:
  bool _internal_has_acceleration_z() const;
  public:
  void clear_acceleration_z();
  float acceleration_z() const;
  void set_acceleration_z(float value);
  private:
  float _internal_acceleration_z() const;
  void _internal_set_acceleration_z(float value);
  public:

  // optional float angle_vel_x = 14;
  bool has_angle_vel_x() const;
  private:
  bool _internal_has_angle_vel_x() const;
  public:
  void clear_angle_vel_x();
  float angle_vel_x() const;
  void set_angle_vel_x(float value);
  private:
  float _internal_angle_vel_x() const;
  void _internal_set_angle_vel_x(float value);
  public:

  // optional float angle_vel_y = 15;
  bool has_angle_vel_y() const;
  private:
  bool _internal_has_angle_vel_y() const;
  public:
  void clear_angle_vel_y();
  float angle_vel_y() const;
  void set_angle_vel_y(float value);
  private:
  float _internal_angle_vel_y() const;
  void _internal_set_angle_vel_y(float value);
  public:

  // optional float angle_vel_z = 16;
  bool has_angle_vel_z() const;
  private:
  bool _internal_has_angle_vel_z() const;
  public:
  void clear_angle_vel_z();
  float angle_vel_z() const;
  void set_angle_vel_z(float value);
  private:
  float _internal_angle_vel_z() const;
  void _internal_set_angle_vel_z(float value);
  public:

  // optional uint32 odometry_function = 17;
  bool has_odometry_function() const;
  private:
  bool _internal_has_odometry_function() const;
  public:
  void clear_odometry_function();
  ::PROTOBUF_NAMESPACE_ID::uint32 odometry_function() const;
  void set_odometry_function(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_odometry_function() const;
  void _internal_set_odometry_function(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 error_code = 18;
  bool has_error_code() const;
  private:
  bool _internal_has_error_code() const;
  public:
  void clear_error_code();
  ::PROTOBUF_NAMESPACE_ID::uint32 error_code() const;
  void set_error_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_error_code() const;
  void _internal_set_error_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float x_wheel_odom = 19;
  bool has_x_wheel_odom() const;
  private:
  bool _internal_has_x_wheel_odom() const;
  public:
  void clear_x_wheel_odom();
  float x_wheel_odom() const;
  void set_x_wheel_odom(float value);
  private:
  float _internal_x_wheel_odom() const;
  void _internal_set_x_wheel_odom(float value);
  public:

  // optional float y_wheel_odom = 20;
  bool has_y_wheel_odom() const;
  private:
  bool _internal_has_y_wheel_odom() const;
  public:
  void clear_y_wheel_odom();
  float y_wheel_odom() const;
  void set_y_wheel_odom(float value);
  private:
  float _internal_y_wheel_odom() const;
  void _internal_set_y_wheel_odom(float value);
  public:

  // optional float yaw_wheel_odom = 21;
  bool has_yaw_wheel_odom() const;
  private:
  bool _internal_has_yaw_wheel_odom() const;
  public:
  void clear_yaw_wheel_odom();
  float yaw_wheel_odom() const;
  void set_yaw_wheel_odom(float value);
  private:
  float _internal_yaw_wheel_odom() const;
  void _internal_set_yaw_wheel_odom(float value);
  public:

  // @@protoc_insertion_point(class_scope:davinci_adas.apa.odometry.Odometry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::apollo::common::Header* header_;
  float x_;
  float y_;
  float z_;
  float pitch_;
  float roll_;
  float yaw_;
  float velocity_x_;
  float velocity_y_;
  float velocity_z_;
  float acceleration_x_;
  float acceleration_y_;
  float acceleration_z_;
  float angle_vel_x_;
  float angle_vel_y_;
  float angle_vel_z_;
  ::PROTOBUF_NAMESPACE_ID::uint32 odometry_function_;
  ::PROTOBUF_NAMESPACE_ID::uint32 error_code_;
  float x_wheel_odom_;
  float y_wheel_odom_;
  float yaw_wheel_odom_;
  friend struct ::TableStruct_odometry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Odometry

// optional .apollo.common.Header header = 1;
inline bool Odometry::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool Odometry::has_header() const {
  return _internal_has_header();
}
inline const ::apollo::common::Header& Odometry::_internal_header() const {
  const ::apollo::common::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::common::Header&>(
      ::apollo::common::_Header_default_instance_);
}
inline const ::apollo::common::Header& Odometry::header() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.header)
  return _internal_header();
}
inline void Odometry::unsafe_arena_set_allocated_header(
    ::apollo::common::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:davinci_adas.apa.odometry.Odometry.header)
}
inline ::apollo::common::Header* Odometry::release_header() {
  _has_bits_[0] &= ~0x00000001u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::apollo::common::Header* Odometry::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:davinci_adas.apa.odometry.Odometry.header)
  _has_bits_[0] &= ~0x00000001u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::apollo::common::Header* Odometry::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::apollo::common::Header* Odometry::mutable_header() {
  // @@protoc_insertion_point(field_mutable:davinci_adas.apa.odometry.Odometry.header)
  return _internal_mutable_header();
}
inline void Odometry::set_allocated_header(::apollo::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:davinci_adas.apa.odometry.Odometry.header)
}

// optional float x = 2;
inline bool Odometry::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Odometry::has_x() const {
  return _internal_has_x();
}
inline void Odometry::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float Odometry::_internal_x() const {
  return x_;
}
inline float Odometry::x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.x)
  return _internal_x();
}
inline void Odometry::_internal_set_x(float value) {
  _has_bits_[0] |= 0x00000002u;
  x_ = value;
}
inline void Odometry::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.x)
}

// optional float y = 3;
inline bool Odometry::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Odometry::has_y() const {
  return _internal_has_y();
}
inline void Odometry::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float Odometry::_internal_y() const {
  return y_;
}
inline float Odometry::y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.y)
  return _internal_y();
}
inline void Odometry::_internal_set_y(float value) {
  _has_bits_[0] |= 0x00000004u;
  y_ = value;
}
inline void Odometry::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.y)
}

// optional float z = 4;
inline bool Odometry::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Odometry::has_z() const {
  return _internal_has_z();
}
inline void Odometry::clear_z() {
  z_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float Odometry::_internal_z() const {
  return z_;
}
inline float Odometry::z() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.z)
  return _internal_z();
}
inline void Odometry::_internal_set_z(float value) {
  _has_bits_[0] |= 0x00000008u;
  z_ = value;
}
inline void Odometry::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.z)
}

// optional float pitch = 5;
inline bool Odometry::_internal_has_pitch() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Odometry::has_pitch() const {
  return _internal_has_pitch();
}
inline void Odometry::clear_pitch() {
  pitch_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float Odometry::_internal_pitch() const {
  return pitch_;
}
inline float Odometry::pitch() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.pitch)
  return _internal_pitch();
}
inline void Odometry::_internal_set_pitch(float value) {
  _has_bits_[0] |= 0x00000010u;
  pitch_ = value;
}
inline void Odometry::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.pitch)
}

// optional float roll = 6;
inline bool Odometry::_internal_has_roll() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Odometry::has_roll() const {
  return _internal_has_roll();
}
inline void Odometry::clear_roll() {
  roll_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float Odometry::_internal_roll() const {
  return roll_;
}
inline float Odometry::roll() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.roll)
  return _internal_roll();
}
inline void Odometry::_internal_set_roll(float value) {
  _has_bits_[0] |= 0x00000020u;
  roll_ = value;
}
inline void Odometry::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.roll)
}

// optional float yaw = 7;
inline bool Odometry::_internal_has_yaw() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Odometry::has_yaw() const {
  return _internal_has_yaw();
}
inline void Odometry::clear_yaw() {
  yaw_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline float Odometry::_internal_yaw() const {
  return yaw_;
}
inline float Odometry::yaw() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.yaw)
  return _internal_yaw();
}
inline void Odometry::_internal_set_yaw(float value) {
  _has_bits_[0] |= 0x00000040u;
  yaw_ = value;
}
inline void Odometry::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.yaw)
}

// optional float velocity_x = 8;
inline bool Odometry::_internal_has_velocity_x() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Odometry::has_velocity_x() const {
  return _internal_has_velocity_x();
}
inline void Odometry::clear_velocity_x() {
  velocity_x_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float Odometry::_internal_velocity_x() const {
  return velocity_x_;
}
inline float Odometry::velocity_x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.velocity_x)
  return _internal_velocity_x();
}
inline void Odometry::_internal_set_velocity_x(float value) {
  _has_bits_[0] |= 0x00000080u;
  velocity_x_ = value;
}
inline void Odometry::set_velocity_x(float value) {
  _internal_set_velocity_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.velocity_x)
}

// optional float velocity_y = 9;
inline bool Odometry::_internal_has_velocity_y() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Odometry::has_velocity_y() const {
  return _internal_has_velocity_y();
}
inline void Odometry::clear_velocity_y() {
  velocity_y_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline float Odometry::_internal_velocity_y() const {
  return velocity_y_;
}
inline float Odometry::velocity_y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.velocity_y)
  return _internal_velocity_y();
}
inline void Odometry::_internal_set_velocity_y(float value) {
  _has_bits_[0] |= 0x00000100u;
  velocity_y_ = value;
}
inline void Odometry::set_velocity_y(float value) {
  _internal_set_velocity_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.velocity_y)
}

// optional float velocity_z = 10;
inline bool Odometry::_internal_has_velocity_z() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Odometry::has_velocity_z() const {
  return _internal_has_velocity_z();
}
inline void Odometry::clear_velocity_z() {
  velocity_z_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline float Odometry::_internal_velocity_z() const {
  return velocity_z_;
}
inline float Odometry::velocity_z() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.velocity_z)
  return _internal_velocity_z();
}
inline void Odometry::_internal_set_velocity_z(float value) {
  _has_bits_[0] |= 0x00000200u;
  velocity_z_ = value;
}
inline void Odometry::set_velocity_z(float value) {
  _internal_set_velocity_z(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.velocity_z)
}

// optional float acceleration_x = 11;
inline bool Odometry::_internal_has_acceleration_x() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool Odometry::has_acceleration_x() const {
  return _internal_has_acceleration_x();
}
inline void Odometry::clear_acceleration_x() {
  acceleration_x_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline float Odometry::_internal_acceleration_x() const {
  return acceleration_x_;
}
inline float Odometry::acceleration_x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.acceleration_x)
  return _internal_acceleration_x();
}
inline void Odometry::_internal_set_acceleration_x(float value) {
  _has_bits_[0] |= 0x00000400u;
  acceleration_x_ = value;
}
inline void Odometry::set_acceleration_x(float value) {
  _internal_set_acceleration_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.acceleration_x)
}

// optional float acceleration_y = 12;
inline bool Odometry::_internal_has_acceleration_y() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool Odometry::has_acceleration_y() const {
  return _internal_has_acceleration_y();
}
inline void Odometry::clear_acceleration_y() {
  acceleration_y_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline float Odometry::_internal_acceleration_y() const {
  return acceleration_y_;
}
inline float Odometry::acceleration_y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.acceleration_y)
  return _internal_acceleration_y();
}
inline void Odometry::_internal_set_acceleration_y(float value) {
  _has_bits_[0] |= 0x00000800u;
  acceleration_y_ = value;
}
inline void Odometry::set_acceleration_y(float value) {
  _internal_set_acceleration_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.acceleration_y)
}

// optional float acceleration_z = 13;
inline bool Odometry::_internal_has_acceleration_z() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool Odometry::has_acceleration_z() const {
  return _internal_has_acceleration_z();
}
inline void Odometry::clear_acceleration_z() {
  acceleration_z_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline float Odometry::_internal_acceleration_z() const {
  return acceleration_z_;
}
inline float Odometry::acceleration_z() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.acceleration_z)
  return _internal_acceleration_z();
}
inline void Odometry::_internal_set_acceleration_z(float value) {
  _has_bits_[0] |= 0x00001000u;
  acceleration_z_ = value;
}
inline void Odometry::set_acceleration_z(float value) {
  _internal_set_acceleration_z(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.acceleration_z)
}

// optional float angle_vel_x = 14;
inline bool Odometry::_internal_has_angle_vel_x() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool Odometry::has_angle_vel_x() const {
  return _internal_has_angle_vel_x();
}
inline void Odometry::clear_angle_vel_x() {
  angle_vel_x_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline float Odometry::_internal_angle_vel_x() const {
  return angle_vel_x_;
}
inline float Odometry::angle_vel_x() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.angle_vel_x)
  return _internal_angle_vel_x();
}
inline void Odometry::_internal_set_angle_vel_x(float value) {
  _has_bits_[0] |= 0x00002000u;
  angle_vel_x_ = value;
}
inline void Odometry::set_angle_vel_x(float value) {
  _internal_set_angle_vel_x(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.angle_vel_x)
}

// optional float angle_vel_y = 15;
inline bool Odometry::_internal_has_angle_vel_y() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool Odometry::has_angle_vel_y() const {
  return _internal_has_angle_vel_y();
}
inline void Odometry::clear_angle_vel_y() {
  angle_vel_y_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline float Odometry::_internal_angle_vel_y() const {
  return angle_vel_y_;
}
inline float Odometry::angle_vel_y() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.angle_vel_y)
  return _internal_angle_vel_y();
}
inline void Odometry::_internal_set_angle_vel_y(float value) {
  _has_bits_[0] |= 0x00004000u;
  angle_vel_y_ = value;
}
inline void Odometry::set_angle_vel_y(float value) {
  _internal_set_angle_vel_y(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.angle_vel_y)
}

// optional float angle_vel_z = 16;
inline bool Odometry::_internal_has_angle_vel_z() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool Odometry::has_angle_vel_z() const {
  return _internal_has_angle_vel_z();
}
inline void Odometry::clear_angle_vel_z() {
  angle_vel_z_ = 0;
  _has_bits_[0] &= ~0x00008000u;
}
inline float Odometry::_internal_angle_vel_z() const {
  return angle_vel_z_;
}
inline float Odometry::angle_vel_z() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.angle_vel_z)
  return _internal_angle_vel_z();
}
inline void Odometry::_internal_set_angle_vel_z(float value) {
  _has_bits_[0] |= 0x00008000u;
  angle_vel_z_ = value;
}
inline void Odometry::set_angle_vel_z(float value) {
  _internal_set_angle_vel_z(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.angle_vel_z)
}

// optional uint32 odometry_function = 17;
inline bool Odometry::_internal_has_odometry_function() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool Odometry::has_odometry_function() const {
  return _internal_has_odometry_function();
}
inline void Odometry::clear_odometry_function() {
  odometry_function_ = 0u;
  _has_bits_[0] &= ~0x00010000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Odometry::_internal_odometry_function() const {
  return odometry_function_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Odometry::odometry_function() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.odometry_function)
  return _internal_odometry_function();
}
inline void Odometry::_internal_set_odometry_function(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00010000u;
  odometry_function_ = value;
}
inline void Odometry::set_odometry_function(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_odometry_function(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.odometry_function)
}

// optional uint32 error_code = 18;
inline bool Odometry::_internal_has_error_code() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool Odometry::has_error_code() const {
  return _internal_has_error_code();
}
inline void Odometry::clear_error_code() {
  error_code_ = 0u;
  _has_bits_[0] &= ~0x00020000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Odometry::_internal_error_code() const {
  return error_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Odometry::error_code() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.error_code)
  return _internal_error_code();
}
inline void Odometry::_internal_set_error_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00020000u;
  error_code_ = value;
}
inline void Odometry::set_error_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.error_code)
}

// optional float x_wheel_odom = 19;
inline bool Odometry::_internal_has_x_wheel_odom() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool Odometry::has_x_wheel_odom() const {
  return _internal_has_x_wheel_odom();
}
inline void Odometry::clear_x_wheel_odom() {
  x_wheel_odom_ = 0;
  _has_bits_[0] &= ~0x00040000u;
}
inline float Odometry::_internal_x_wheel_odom() const {
  return x_wheel_odom_;
}
inline float Odometry::x_wheel_odom() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.x_wheel_odom)
  return _internal_x_wheel_odom();
}
inline void Odometry::_internal_set_x_wheel_odom(float value) {
  _has_bits_[0] |= 0x00040000u;
  x_wheel_odom_ = value;
}
inline void Odometry::set_x_wheel_odom(float value) {
  _internal_set_x_wheel_odom(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.x_wheel_odom)
}

// optional float y_wheel_odom = 20;
inline bool Odometry::_internal_has_y_wheel_odom() const {
  bool value = (_has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline bool Odometry::has_y_wheel_odom() const {
  return _internal_has_y_wheel_odom();
}
inline void Odometry::clear_y_wheel_odom() {
  y_wheel_odom_ = 0;
  _has_bits_[0] &= ~0x00080000u;
}
inline float Odometry::_internal_y_wheel_odom() const {
  return y_wheel_odom_;
}
inline float Odometry::y_wheel_odom() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.y_wheel_odom)
  return _internal_y_wheel_odom();
}
inline void Odometry::_internal_set_y_wheel_odom(float value) {
  _has_bits_[0] |= 0x00080000u;
  y_wheel_odom_ = value;
}
inline void Odometry::set_y_wheel_odom(float value) {
  _internal_set_y_wheel_odom(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.y_wheel_odom)
}

// optional float yaw_wheel_odom = 21;
inline bool Odometry::_internal_has_yaw_wheel_odom() const {
  bool value = (_has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline bool Odometry::has_yaw_wheel_odom() const {
  return _internal_has_yaw_wheel_odom();
}
inline void Odometry::clear_yaw_wheel_odom() {
  yaw_wheel_odom_ = 0;
  _has_bits_[0] &= ~0x00100000u;
}
inline float Odometry::_internal_yaw_wheel_odom() const {
  return yaw_wheel_odom_;
}
inline float Odometry::yaw_wheel_odom() const {
  // @@protoc_insertion_point(field_get:davinci_adas.apa.odometry.Odometry.yaw_wheel_odom)
  return _internal_yaw_wheel_odom();
}
inline void Odometry::_internal_set_yaw_wheel_odom(float value) {
  _has_bits_[0] |= 0x00100000u;
  yaw_wheel_odom_ = value;
}
inline void Odometry::set_yaw_wheel_odom(float value) {
  _internal_set_yaw_wheel_odom(value);
  // @@protoc_insertion_point(field_set:davinci_adas.apa.odometry.Odometry.yaw_wheel_odom)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace odometry
}  // namespace apa
}  // namespace davinci_adas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_odometry_2eproto
